"""forma y desvio de relaciones

Revision ID: 3c32cd2a8dc4
Revises: 785c34c85064
Create Date: 2026-09-22 20:19:43.448572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c32cd2a8dc4'
down_revision: Union[str, Sequence[str], None] = '785c34c85064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relaciones', sa.Column('forma', sa.String(length=10), nullable=True))
    op.add_column('relaciones', sa.Column('desvio_x', sa.Float(), nullable=True))
    op.add_column('relaciones', sa.Column('desvio_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relaciones', 'desvio_y')
    op.drop_column('relaciones', 'desvio_x')
    op.drop_column('relaciones', 'forma')
    # ### end Alembic commands ###
