"""crear tablas del diagrama de clases uml

Revision ID: 785c34c85064
Revises: e7895721e3b5
Create Date: 2026-09-12 22:46:54.437146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785c34c85064'
down_revision: Union[str, Sequence[str], None] = 'e7895721e3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clases_uml',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('estereotipo', sa.String(length=50), nullable=True),
    sa.Column('es_abstracta', sa.Boolean(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atributos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_clase', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('visibilidad', sa.Enum('PUBLICO', 'PRIVADO', 'PROTEGIDO', 'PAQUETE', name='visibilidadmiembro'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_clase'], ['clases_uml.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_clase', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('parametros', sa.String(length=255), nullable=True),
    sa.Column('tipo_retorno', sa.String(length=100), nullable=True),
    sa.Column('visibilidad', sa.Enum('PUBLICO', 'PRIVADO', 'PROTEGIDO', 'PAQUETE', name='visibilidadmiembro'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_clase'], ['clases_uml.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relaciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_clase_origen', sa.String(length=36), nullable=False),
    sa.Column('id_clase_destino', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('ASOCIACION', 'HERENCIA', 'AGREGACION', 'COMPOSICION', name='tiporelacion'), nullable=False),
    sa.Column('etiqueta', sa.String(length=100), nullable=True),
    sa.Column('multiplicidad_origen', sa.String(length=20), nullable=True),
    sa.Column('multiplicidad_destino', sa.String(length=20), nullable=True),
    sa.Column('handle_origen', sa.String(length=10), nullable=True),
    sa.Column('handle_destino', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_clase_destino'], ['clases_uml.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_clase_origen'], ['clases_uml.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relaciones')
    op.drop_table('metodos')
    op.drop_table('atributos')
    op.drop_table('clases_uml')
    # ### end Alembic commands ###
